const lang = {
  english: {
    name: "Name: ",
    email: "Email: ",
    fullName: "Full Name",
    emailAddress: "Email Address",
    password: "Password",
    signIn: "Sign In",
    signInNow: "Sign In Now",
    signUp: "Sign Up",
    signUpNow: "Sign Up Now",
    newToNetflix: "New to Netflix ",
    alreadyRegistered: "Already Registered ",
    signOut: "Sign Out",
    homePage: "Home Page",
    gptSearchButton: "GPT Search",
    search: "Search",
    gptSearchPlaceholder: "What would you like to watch today?",
  },
  hindi: {
    name: "नाम: ",
    email: "ईमेल: ",
    fullName: "पूरा नाम",
    emailAddress: "मेल पता",
    password: "पासवर्ड",
    signIn: "साइन इन करें",
    signInNow: "अब साइन इन करो",
    signUp: "साइन अप करें",
    signUpNow: "अभी साइनअप करें",
    newToNetflix: "नेटफ्लिक्स पर नया ",
    alreadyRegistered: "पहले से ही पंजीकृत ",
    signOut: "साइन आउट",
    gptSearchButton: "जीपीटी खोज",
    homePage: "होम पेज",
    search: "खोज",
    gptSearchPlaceholder: "आज आप क्या देखना चाहेंगे?",
  },
  telugu: {
    name: "పేరు: ",
    email: "ఇమెయిల్: ",
    fullName: "పూర్తి పేరు",
    emailAddress: "ఇమెయిల్ చిరునామా",
    password: "పాస్వర్డ్",
    signIn: "సైన్ ఇన్",
    signInNow: "ఇప్పుడే సైన్ ఇన్ చేయండి",
    signUp: "సైన్ అప్ చేయండి",
    signUpNow: "ఇప్పుడే సైన్ అప్ చేయండి",
    newToNetflix: "Netflixకి కొత్త ",
    alreadyRegistered: "ఇప్పటికే నమోదైంది ",
    signOut: "సైన్ అవుట్",
    gptSearchButton: "GPT శోధన",
    homePage: "హోమ్ పేజీ",
    search: "శోధించండి",
    gptSearchPlaceholder: "మీరు ఈరోజు ఏమి చూడాలనుకుంటున్నారు?",
  },
};

export default lang;
